name: Build macOS Vulkan
run-name: Build macOS Vulkan | ${{ github.event.pull_request && format('{0} -> {1} by {2} (PR {3})', github.head_ref, github.base_ref, github.actor, github.event.pull_request.number) || github.event_name == 'workflow_dispatch' && format('{0} by {1} [manual]', github.ref_name, github.actor) || format('{0} by {1}', github.ref_name, github.actor) }}

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Debug, Release ]
        enable-glfw: [ GLFW=ON, GLFW=OFF ]
        enable-imgui: [ IMGUI=ON, IMGUI=OFF ]
        build-examples: [ EXAMPLES=ON, EXAMPLES=OFF ]

        exclude:
          - build-examples: EXAMPLES=ON
            enable-imgui: IMGUI=OFF
          - build-examples: EXAMPLES=ON
            enable-glfw: GLFW=OFF

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake -S ${{ github.workspace }} -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -DGFX_BUILD_METAL=OFF
          -DGFX_BUILD_VULKAN=ON
          -DGFX_ENABLE_${{ matrix.enable-glfw }}
          -DGFX_ENABLE_${{ matrix.enable-imgui }}
          -DGFX_BUILD_${{ matrix.build-examples }}

      - name: Build
        run: cmake --build build --config Release
